---
- hosts: '{{ target }}'
  gather_facts: no
  become: true
  vars_files:
  - '{{ user_file }}'
  roles:
    # - setup
    # - install_zsh
    #- install_caddy
    # - install_awscli
    # - security
